name: Deploy Streamlit App to Azure

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: asfaltregistry.azurecr.io  
        username: ${{ secrets.AZURE_USERNAME }}
        password: ${{ secrets.AZURE_PASSWORD  }}

    - name: Build and push Docker image
      run: |
        docker build -t asfaltregistry.azurecr.io/asfaltcalculator:latest .
        docker push asfaltregistry.azurecr.io/asfaltcalculator:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: asfaltcalculator  # naam van je Web App
        images: asfaltregistry.azurecr.io/asfaltcalculator:latest
